<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sipd_mwajib_pajak_model extends CI_Model
{

    public $table = 'sipd_mwajib_pajak';
    public $id = 'NPWPD';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('NPWPD', $q);
	$this->db->or_like('Nm_BadanUsaha', $q);
	$this->db->or_like('Alamat_Usaha', $q);
	$this->db->or_like('Alamat_No_Usaha', $q);
	$this->db->or_like('Rt_Usaha', $q);
	$this->db->or_like('Rw_Usaha', $q);
	$this->db->or_like('Rk_Usaha', $q);
	$this->db->or_like('Kd_Wil_Usaha', $q);
	$this->db->or_like('Telp_Usaha', $q);
	$this->db->or_like('Kotak_Pos', $q);
	$this->db->or_like('Kode_Usaha', $q);
	$this->db->or_like('Modal_Kerja', $q);
	$this->db->or_like('Nm_Pemilik', $q);
	$this->db->or_like('Jabatan', $q);
	$this->db->or_like('Alamat_Pemilik', $q);
	$this->db->or_like('Alamat_No_Pemilik', $q);
	$this->db->or_like('Rt_Pemilik', $q);
	$this->db->or_like('Rw_Pemilik', $q);
	$this->db->or_like('Rk_Pemilik', $q);
	$this->db->or_like('Kd_Wil_Pemilik', $q);
	$this->db->or_like('Telp_Usaha_Pemilik', $q);
	$this->db->or_like('Kotak_Pos_Pemilik', $q);
	$this->db->or_like('Jml_Izin', $q);
	$this->db->or_like('lAktif', $q);
	$this->db->or_like('Keterangan', $q);
	$this->db->or_like('TglNonAktif', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('NPWPD', $q);
	$this->db->or_like('Nm_BadanUsaha', $q);
	$this->db->or_like('Alamat_Usaha', $q);
	$this->db->or_like('Alamat_No_Usaha', $q);
	$this->db->or_like('Rt_Usaha', $q);
	$this->db->or_like('Rw_Usaha', $q);
	$this->db->or_like('Rk_Usaha', $q);
	$this->db->or_like('Kd_Wil_Usaha', $q);
	$this->db->or_like('Telp_Usaha', $q);
	$this->db->or_like('Kotak_Pos', $q);
	$this->db->or_like('Kode_Usaha', $q);
	$this->db->or_like('Modal_Kerja', $q);
	$this->db->or_like('Nm_Pemilik', $q);
	$this->db->or_like('Jabatan', $q);
	$this->db->or_like('Alamat_Pemilik', $q);
	$this->db->or_like('Alamat_No_Pemilik', $q);
	$this->db->or_like('Rt_Pemilik', $q);
	$this->db->or_like('Rw_Pemilik', $q);
	$this->db->or_like('Rk_Pemilik', $q);
	$this->db->or_like('Kd_Wil_Pemilik', $q);
	$this->db->or_like('Telp_Usaha_Pemilik', $q);
	$this->db->or_like('Kotak_Pos_Pemilik', $q);
	$this->db->or_like('Jml_Izin', $q);
	$this->db->or_like('lAktif', $q);
	$this->db->or_like('Keterangan', $q);
	$this->db->or_like('TglNonAktif', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Sipd_mwajib_pajak_model.php */
/* Location: ./application/models/Sipd_mwajib_pajak_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-03-26 19:40:24 */
/* http://harviacode.com */