<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Siup_order_model extends CI_Model
{

    public $table = 'siup_order';
    public $id = 'id_order';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_order', $q);
	$this->db->or_like('date', $q);
	$this->db->or_like('id_unit', $q);
	$this->db->or_like('id_product', $q);
	$this->db->or_like('stver', $q);
	$this->db->or_like('stacc', $q);
	$this->db->or_like('stpch', $q);
	$this->db->or_like('stord', $q);
	$this->db->or_like('ket', $q);
	$this->db->or_like('tgl_ver', $q);
	$this->db->or_like('tgl_acc', $q);
	$this->db->or_like('tgl_pch', $q);
	$this->db->or_like('tgl_terima', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_order', $q);
	$this->db->or_like('date', $q);
	$this->db->or_like('id_unit', $q);
	$this->db->or_like('id_product', $q);
	$this->db->or_like('stver', $q);
	$this->db->or_like('stacc', $q);
	$this->db->or_like('stpch', $q);
	$this->db->or_like('stord', $q);
	$this->db->or_like('ket', $q);
	$this->db->or_like('tgl_ver', $q);
	$this->db->or_like('tgl_acc', $q);
	$this->db->or_like('tgl_pch', $q);
	$this->db->or_like('tgl_terima', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Siup_order_model.php */
/* Location: ./application/models/Siup_order_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-03-28 17:17:20 */
/* http://harviacode.com */